[build]
builder = "NIXPACKS"
buildCommand = "cd pleasantcovedesign/server && npm ci && npm run build"

[deploy]
startCommand = "cd pleasantcovedesign/server && node dist/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[service]
port = 3000
