# Railway configuration
# This file forces Railway to rebuild the application

[build]
builder = "NIXPACKS"
buildCommand = "cd pleasantcovedesign/server && npm install && npm run build"

[deploy]
startCommand = "cd pleasantcovedesign/server && node dist/index.js"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[service]
port = 3000
