# Railway configuration
# This file forces Railway to rebuild the application

[build]
builder = "NIXPACKS"
buildCommand = "cd pleasantcovedesign/server && npm ci && npm run build:with-admin"

[deploy]
startCommand = "cd pleasantcovedesign/server && node index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[service]
port = 3000